<a href="https://colab.research.google.com/github/gcasaldi/experiments/blob/main/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Definiamo le matrici di spin nella base |z+>, |z->
ħ = 1  # Consideriamo ħ=1 per semplicità
Sx = (ħ / 2) * np.array([[0, 1], [1, 0]])
Sy = (ħ / 2) * np.array([[0, -1j], [1j, 0]])
Sz = (ħ / 2) * np.array([[1, 0], [0, -1]])

# Definizione degli autostati di Sx nella base di Sz
x_plus = (1 / np.sqrt(2)) * np.array([1, 1])
x_minus = (1 / np.sqrt(2)) * np.array([1, -1])

# Costruzione della matrice di cambiamento di base
U = np.column_stack((x_plus, x_minus))
U_inv = np.linalg.inv(U)  # Inversa di U

# Trasformiamo le matrici degli operatori di spin nella nuova base
Sx_new = U_inv @ Sx @ U
Sy_new = U_inv @ Sy @ U
Sz_new = U_inv @ Sz @ U

# Stampiamo i risultati
print("Sx nella nuova base:")
print(Sx_new)
print("\nSy nella nuova base:")
print(Sy_new)
print("\nSz nella nuova base:")
print(Sz_new)


Sx nella nuova base:
[[ 5.00000000e-01  5.07326818e-18]
 [-5.07326818e-18 -5.00000000e-01]]

Sy nella nuova base:
[[0.+5.07326818e-18j 0.+5.00000000e-01j]
 [0.-5.00000000e-01j 0.-5.07326818e-18j]]

Sz nella nuova base:
[[5.07326818e-18 5.00000000e-01]
 [5.00000000e-01 5.07326818e-18]]


In [2]:
import numpy as np

# Definizione della matrice di trasformazione unitaria U
u11, u12, u21, u22 = 1, 2, 3, 4  # Sostituire con i valori specifici
U = np.array([[u11, u12],
              [u21, u22]])

# Definizione della matrice di riflessione nel sistema di base φ (R_phi)
r11_phi, r12_phi, r21_phi, r22_phi = 1, 0, 0, -1  # Sostituire con i valori specifici
R_phi = np.array([[r11_phi, r12_phi],
                  [r21_phi, r22_phi]])

# Calcolare la matrice di riflessione nel sistema di base ψ (R_psi)
U_inv = np.linalg.inv(U)  # Calcolare l'inversa della matrice U
R_psi = np.dot(U, np.dot(R_phi, U_inv))  # Trasformazione di similarità

# Visualizzare i risultati
print("Matrice di riflessione nel sistema di base ψ (R_psi):")
print(R_psi)

# Verifica della trasformazione di similarità: R_psi = U * R_phi * U^-1
if np.allclose(np.dot(U, np.dot(R_phi, U_inv)), R_psi):
    print("\nLe matrici sono correlate tramite una trasformazione di similarità.")
else:
    print("\nLe matrici non sono correlate tramite una trasformazione di similarità.")

Matrice di riflessione nel sistema di base ψ (R_psi):
[[ -5.   2.]
 [-12.   5.]]

Le matrici sono correlate tramite una trasformazione di similarità.


SyntaxError: unexpected character after line continuation character (<ipython-input-10-979f475c83b0>, line 1)